services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tickhawk
      - BASE_URL=http://localhost
      - S3_PROVIDER=local
      - PORT=3333
      - LOCAL_UPLOAD_PATH=/app/uploads
      - LOG_LEVEL=info
      - ENABLE_SWAGGER=true
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRATION=60m
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_SECURE=true
      - EMAIL_USERNAME=test
      - EMAIL_PASSWORD=test
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:3333
    ports:
      - "4444:80"
    depends_on:
      - api
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
  uploads_data: